version: "2.1"

orbs:
  orb-tools: circleci/orb-tools@8.27.1
  cli: circleci/circleci-cli@0.1.4

jobs:
  validate:
    executor: cli/default
    steps:
      - checkout
      - run: circleci orb validate src/orb.yml

workflows:
  test_orb:
    jobs:
      - validate
      - orb-tools/lint
      - orb-tools/test-in-builds:
          requires:
            - validate
          orb-location: src/orb.yml
          orb-name: aws-opsworks-deploy
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/test.yml
